import { NotificationResendButton } from "@/components/admin/notification-resend-button";
import { prisma } from "@/lib/prisma";
import Link from "next/link";

export default async function AdminNotificationsPage() {
  const [jobs, staffJobs] = await Promise.all([
    prisma.notificationJob.findMany({ include: { appointment: { include: { patient: true, slot: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.staffNotificationJob.findMany({ include: { contactMessage: true }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const stateClass = (status: string) => status === "sent" ? "bg-secondary text-secondary-foreground" : status === "failed" || status === "skipped" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-800";
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[0.16em] text-primary">NOTIFICATIONS</p><h1 className="mt-1 text-2xl font-bold">通知センター</h1><p className="mt-2 text-sm text-muted-foreground">患者向けメールと、受付担当者向け通知を確認します。</p></div><Link href="/admin/settings/notifications" className="rounded-lg border px-4 py-3 text-sm font-bold hover:bg-secondary">通知設定</Link></div><section className="mt-6 overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b bg-muted/40 px-4 py-3 text-sm font-bold">患者向け通知</div>{jobs.length ? <div className="divide-y">{jobs.map((job) => <div key={job.id} className="grid gap-3 px-4 py-4 text-sm sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-bold">{job.type === "confirmation" ? "予約確定" : job.type === "reminder" ? "前日リマインド" : job.type === "cancellation" ? "取消" : "日時変更"}　{job.appointment?.patient.name ?? "患者不明"}</p><p className="mt-1 text-xs text-muted-foreground">{job.appointment?.patient.email ?? "メールアドレス未登録"}　／　{job.lastError ?? job.providerMessageId ?? "未処理"}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${stateClass(job.status)}`}>{job.status}</span><NotificationResendButton id={job.id} /></div>)}</div> : <p className="p-8 text-center text-sm text-muted-foreground">通知履歴はありません。</p>}</section><section className="mt-6 overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b bg-muted/40 px-4 py-3 text-sm font-bold">受付担当者向け通知</div>{staffJobs.length ? <div className="divide-y">{staffJobs.map((job) => <div key={job.id} className="grid gap-3 px-4 py-4 text-sm sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-bold">{job.type === "contact" ? "新しいお問い合わせ" : job.type === "appointment_change" ? "予約変更・取消" : job.type === "email_failed" ? "メール送信失敗" : "受付タスク"}{job.contactMessage ? `　${job.contactMessage.name}様` : ""}</p><p className="mt-1 text-xs text-muted-foreground">{job.createdAt.toLocaleString("ja-JP")}　／　{job.lastError ?? "処理済み"}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${stateClass(job.status)}`}>{job.status}</span></div>)}</div> : <p className="p-8 text-center text-sm text-muted-foreground">受付通知はありません。</p>}</section></div>;
}
