import Link from "next/link";

import { getPatientCardLookupHash } from "@/lib/pii";
import { prisma } from "@/lib/prisma";

export default async function AdminPatientsPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const query = ((await searchParams).q ?? "").trim();
  const patients = query ? await prisma.patient.findMany({ where: { OR: [{ name: { contains: query, mode: "insensitive" } }, { nameKana: { contains: query, mode: "insensitive" } }, { phone: { contains: query } }, { patientCardNumberLookupHash: getPatientCardLookupHash(query.replace(/[\s-]/g, "")) }, { chartNumberLookupHash: getPatientCardLookupHash(query.replace(/[\s-]/g, "")) }] }, orderBy: { updatedAt: "desc" }, take: 50 }) : await prisma.patient.findMany({ orderBy: { updatedAt: "desc" }, take: 30 });
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-[0.16em] text-primary">PATIENTS</p><h1 className="mt-1 text-2xl font-bold">患者台帳</h1><p className="mt-1 text-sm text-muted-foreground">診察券番号・カルテ患者番号・氏名から検索します。</p></div><Link href="/admin/patients/new" className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">＋患者を登録</Link></div><form className="mt-6 flex gap-2"><input name="q" defaultValue={query} placeholder="例：山田、090、診察券番号" className="h-12 min-w-0 flex-1 rounded-lg border bg-card px-3" /><button type="submit" className="rounded-lg border px-5 font-bold hover:bg-secondary">検索</button></form><div className="mt-6 overflow-hidden rounded-2xl border bg-card shadow-sm">{patients.length ? <div className="divide-y">{patients.map((patient) => <Link key={patient.id} href={`/admin/patients/${patient.id}`} className="grid gap-2 px-4 py-4 hover:bg-secondary/30 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><span><span className="font-bold">{patient.name}</span>{patient.nameKana && <span className="ml-2 text-xs text-muted-foreground">{patient.nameKana}</span>}<span className="mt-1 block text-xs text-muted-foreground">{patient.phone}{patient.birthDate ? `　${patient.birthDate}` : ""}</span></span><span className="text-xs text-muted-foreground">診察券 {patient.patientCardNumberLast4 ? `••••${patient.patientCardNumberLast4}` : "未登録"}</span><span className={`text-xs font-bold ${patient.chartLinkStatus === "linked" ? "text-primary" : "text-amber-700"}`}>{patient.chartLinkStatus === "linked" ? "カルテ紐付済" : "カルテ未紐付"}</span></Link>)}</div> : <p className="p-8 text-center text-sm text-muted-foreground">患者が見つかりません。</p>}</div></div>;
}
